version: "3.9"
services:
  pg:
    image: postgres:12
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgreUser1
      - POSTGRES_PASSWORD=postgrePassword
    ports:
      - '5432:5432'
